name: CI

on:
  - push
  - pull_request

jobs:
  format:
    name: Format and compile with warnings as errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28.0"
          elixir-version: "1.18.4"

      - name: Install dependencies
        run: mix deps.get

      - name: Check mix format
        run: mix format --check-formatted

      - name: Compile with warnings as errors
        run: mix compile --warnings-as-errors

  analysis:
    name: Run static code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28.0"
          elixir-version: "1.18.4"

      - name: Install dependencies
        run: mix deps.get

      - name: Analyze code
        run: mix credo --strict

  test:
    name: Test Elixir ${{ matrix.elixir }}, OTP ${{ matrix.erlang }}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - erlang: "28.0"
            elixir: "1.18.4"
            os: "ubuntu-24.04"
          - erlang: "26.1"
            elixir: "1.15.7"
            os: "ubuntu-24.04"
          - erlang: "24.2"
            elixir: "1.12.3"
            os: "ubuntu-22.04"
          - erlang: "24.2"
            elixir: "1.13.4"
            os: "ubuntu-22.04"

    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlang }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Run unit tests
        run: mix test --trace --exclude functional

      - name: Run functional tests
        run: mix test --trace --only functional
